[package]
name = "swc-plugin-reanimated"
version = "0.1.0"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = ""
license = "MIT"
repository = "https://github.com/software-mansion/react-native-reanimated"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc_core = { version = "0.43.23", features = ["plugin_transform"] }
swc-reanimated-worklets-visitor = { version = "0.1.0", path = "../swc-reanimated-worklets-visitor" }
serde = "1.0.137"
serde_json = "1.0.81"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
