name: Lint SWC plugin
on:
  pull_request:
    paths:
      - '.github/workflows/lint-swc-plugin.yml'
      - 'plugin-swc/*'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: lint-swc-plugin-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Use cargo
        uses: actions-rs/cargo@v1
      - name: Lint
        working-directory: plugin-swc
        run: cargo fmt --all -- --check
